### ISSUE TITLE
Add pre-commit check on CI

### ISSUE THREAD

**Issue by aericson** [vintasoftware/vinta-boilerplate#51]
"Usage in Continuous Integration
pre-commit can also be used as a tool for continuous integration. For instance, adding `pre-commit run --all-files` as a CI step will ensure everything stays in tip-top shape. "

@fjsj should we do this check on CI or do we have a reason not to do it?

**Comment by fjsj** [comment]
yes
cinnamon does it
use:
`SKIP=flake8,isort pre-commit run --all-files`

2017-03-02 14:25 GMT-03:00 André Ericson <notifications@github.com>:
